### ISSUE TITLE
Question on Transform types

### ISSUE THREAD

**Issue by Tariq-Abuhashim** [emiliofidalgo/bimos#12]
Hello Emilio;

There are 4 types declared in Transform.h , but only two have been implemented in HomographyEstimator.cpp
The two missing ones are PERSPECTIVE and ROTATIONAL.
Is that right?

**Comment by emiliofidalgo** [comment]
Hi Tariq,

That's correct. In our work, we finally assumed, at most, a similarity transformation between frames. Therefore, it seems that I didn't implement the remaining cases, since we didn't need them.

**Comment by dearchonger** [comment]
Hi Emilio;
How can I include the BimosConfig.h file.

**Comment by dearchonger** [comment]
Hello Emilio;
I can not find any file named BimosConfig.h in bimos folder, so there is an import error in my project...
 I was download the code of  master branch, is there anything missing?

**Comment by emiliofidalgo** [comment]
Hi @dearchonger,

There is no file named BimosConfig.h in the package. Could you please provide a more detailed info about the error you get?

**Comment by Tariq-Abuhashim** [comment]
BimosConfig.h is generated by catkin.

**Comment by dearchonger** [comment]
> BimosConfig.h is generated by catkin.

This helps me. Thank you very much.
