### ISSUE TITLE
Hi  Do you have any idea to make the result picture orthographic?

### ISSUE THREAD

**Issue by MerlotQ** [emiliofidalgo/bimos#8]
If I got the GPS info of each image, can I get an orthophoto from the result? Like a tile on a map?

**Comment by emiliofidalgo** [comment]
Hi!

BIMOS was not devised with this idea in mind. However, I think you can adapt the code to do this: instead of performing the blending step, you can use the topology generated by BIMOS to stitch the images together in your own application according to the GPS coordinates of each image.
