### ISSUE TITLE
OpenCV dependency for both obindex and bimos

### ISSUE THREAD

**Issue by Tariq-Abuhashim** [emiliofidalgo/bimos#9]
Which version of OpenCV do both obindex and bimos depend on?

**Comment by emiliofidalgo** [comment]
Originally it was developed using OpenCV 2.4, but there is a branch called **kinetic** (in both repositories) including the modifications required to be used with OpenCV 3.1.

**Comment by Tariq-Abuhashim** [comment]
Cool, thanks.
